# Generated by Django 3.0.8 on 2021-02-01 18:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rastapuchoapp', '0003_blog_blogslug'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogslug',
            name='image_url',
            field=models.CharField(default=django.utils.timezone.now, max_length=1000),
            preserve_default=False,
        ),
    ]
