# Generated by Django 3.1.3 on 2021-02-02 17:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rastapuchoapp', '0005_blogslug_published_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('message', models.TextField()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 23, 14, 47, 98236), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='blogslug',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 23, 14, 47, 98236), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='blogslug',
            name='slug_content',
            field=models.CharField(max_length=250),
        ),
        migrations.AlterField(
            model_name='blogslug',
            name='slug_title',
            field=models.CharField(max_length=100),
        ),
    ]
