# Generated by Django 3.1.3 on 2021-02-02 17:47

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rastapuchoapp', '0006_auto_20210202_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='your_image',
            field=models.ImageField(default=datetime.datetime(2021, 2, 2, 17, 47, 3, 465305, tzinfo=utc), upload_to='reviews'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogslug',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 23, 16, 54, 638176), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='card',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 23, 16, 54, 634181), verbose_name='date published'),
        ),
    ]
