# Generated by Django 3.1.3 on 2021-02-02 18:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('rastapuchoapp', '0010_auto_20210202_2333'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date',
            field=models.DateField(auto_now_add=True, default=datetime.datetime(2021, 2, 2, 18, 25, 39, 824047, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogslug',
            name='published_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 23, 55, 18, 426044), verbose_name='date published'),
        ),
        migrations.AlterField(
            model_name='card',
            name='creation_date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 2, 23, 55, 18, 426044), verbose_name='date published'),
        ),
    ]
